<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-09-28 13:50
=======
# Generated by Django 3.2.6 on 2021-10-01 13:39
>>>>>>> 44f4f29735af525554edde251166c966b54bb304

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language_book', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='example: 2017-03-14')),
<<<<<<< HEAD
                ('published_date', models.DateField(help_text='example: 2017-03-14')),
=======
                ('published_date', models.DateField(help_text='example: 2017-03-14', max_length=10)),
>>>>>>> 44f4f29735af525554edde251166c966b54bb304
                ('isbn13_number', models.IntegerField(blank=True, null=True)),
                ('authors_name', models.CharField(default='unknown', max_length=300)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('link_book_cover', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
