# Generated by Django 3.2.6 on 2021-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language_book', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='example: 2017-03-14')),
                ('published_date', models.CharField(default='unknown', help_text='example: 2017-03-14', max_length=40)),
                ('isbn13_number', models.IntegerField()),
                ('authors_name', models.CharField(default='unknown', max_length=300)),
                ('page_number', models.IntegerField(default=0)),
                ('link_book_cover', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
