# Generated by Django 3.2.6 on 2021-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13_number',
            field=models.IntegerField(null=True),
        ),
    ]
