# Generated by Django 3.2.6 on 2021-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_alter_book_isbn13_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13_number',
            field=models.IntegerField(max_length=13, null=True),
        ),
    ]
