# Generated by Django 3.2.6 on 2021-10-07 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_alter_book_isbn13_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
