# Generated by Django 3.2.6 on 2021-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_alter_book_isbn13_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(help_text='example: dd/mm/yyyy', max_length=10),
        ),
    ]
