# Generated by Django 3.2.6 on 2021-10-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_auto_20211016_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(help_text='example: 2017-03-14'),
        ),
    ]
